"""Add category to payment

Revision ID: 0a735765ab21
Revises: 7492cfbf2119
Create Date: 2026-10-09 14:19:42.999844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a735765ab21'
down_revision = '7492cfbf2119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=20), server_default='rent', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
