"""Add termination fields to lease

Revision ID: 36ee7096057f
Revises: e62b16536769
Create Date: 2026-10-08 13:15:50.859607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ee7096057f'
down_revision = 'e62b16536769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.add_column(sa.Column('termination_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('terminated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lease', schema=None) as batch_op:
        batch_op.drop_column('terminated_at')
        batch_op.drop_column('termination_reason')

    # ### end Alembic commands ###
