"""Add property_expense table

Revision ID: 7492cfbf2119
Revises: 36ee7096057f
Create Date: 2026-10-08 16:11:38.260905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7492cfbf2119'
down_revision = '36ee7096057f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("category in ('down_payment', 'closing_costs', 'mortgage', 'hoa', 'property_tax', 'insurance', 'utilities', 'management_fee', 'remodel', 'legal', 'other')", name='ck_property_expense_category'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_expense')
    # ### end Alembic commands ###
