"""Replace tenant_id with reported_by on maintenance_request

Revision ID: e62b16536769
Revises: 4fc04cd461c6
Create Date: 2026-09-29 15:43:37.316776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62b16536769'
down_revision = '4fc04cd461c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reported_by', sa.String(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('maintenance_request_tenant_id_fkey'), type_='foreignkey')
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('maintenance_request_tenant_id_fkey'), 'tenant', ['tenant_id'], ['id'])
        batch_op.drop_column('reported_by')

    # ### end Alembic commands ###
