"""Initial migration - create all tables

Revision ID: ea31bee9cc13
Revises: 
Create Date: 2026-09-02 15:34:13.315218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea31bee9cc13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip', sa.String(length=100), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('property_type', sa.String(length=100), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('area', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_occupied', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('driver_license', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emergency_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lease',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('monthly_rent', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rent_due_date', sa.Integer(), nullable=False),
    sa.Column('refundable_deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nonrefundable_deposit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cars', sa.Integer(), nullable=True),
    sa.Column('pets', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submission_time', sa.DateTime(), nullable=True),
    sa.Column('resolution_time', sa.DateTime(), nullable=True),
    sa.Column('material_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('paid_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['lease.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lease_tenant',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['lease.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'lease_id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('rent_due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lease_id'], ['lease.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('lease_tenant')
    op.drop_table('dependence')
    op.drop_table('maintenance_request')
    op.drop_table('lease')
    op.drop_table('image')
    op.drop_table('emergency_contact')
    op.drop_table('tenant')
    op.drop_table('property')
    # ### end Alembic commands ###
